easy_admin:
    entities:
        User:
            class: App\Entity\User
        Game:
            class: App\Entity\Game
        Party:
            class: App\Entity\Party
        Event:
            class: App\Entity\Event
        Association:
            class: App\Entity\Association
        Commentary:
            class: App\Entity\Commentary
        OpenReport:
            class: App\Entity\Report
            list:
                dql_filter: 'entity.solved = false'
        ClosedReport:
            class: App\Entity\Report
            list:
                dql_filter: 'entity.solved = true'
    user:
        display_avatar: false
        name_property_path: 'pseudonym'
