easy_admin:
    site_name: 'Annonce ton JDR <em><strong>Admin</strong></em>'
    
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    user:
        display_avatar: false
        name_property_path: 'pseudonym'
    list:
        actions: ['show']
    entities:
        User:
            disabled_actions: ['edit', 'new']
            class: App\Entity\User
            list:
                fields: ['pseudonym', 'email', 'association', 'reports','suspend']
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
                fields: ['pseudonym', 'email', 'association','secretR', 'reports', 'suspend']
                actions:
                    - { name: 'add_Admin', type: 'route', icon: 'plus-square', css_class: 'btn btn-primary', template: 'admin/admin_add_action.html.twig'}
                    - { name: 'remove_Admin', type: 'route', icon: 'minus-square', css_class: 'btn btn btn-danger', template: 'admin/admin_remove_action.html.twig' }
                    - { name: 'activate_Admin', type: 'route', icon: 'plus-square', css_class: 'btn btn-primary', template: 'admin/activate_action.html.twig'}
                    - { name: 'suspend_Admin', type: 'route', icon: 'minus-square', css_class: 'btn btn btn-danger', template: 'admin/suspend_action.html.twig' }
            search:
                fields: ['pseudonym', 'email', 'association.name', 'roles']
        Game:
            class: App\Entity\Game
            list:
                fields: ['name','image_url']
            show:
                fields: ['name','image_url']
        Party:
            disabled_actions: ['edit', 'new']
            class: App\Entity\Party
            list:
                fields: ['partyName','owner', 'date', 'gameName', 'reports']
            show:
                fields: ['partyName','owner', 'date', 'alreadySubscribed', 'maxPlayer', 'minor', 'gameName', 'gameEdition', 'nameScenario', 'scenarioEdition', 'openedCampaign', 'gameDescription', 'online', 'registeredPlayers', 'address', 'commentaries', 'reports']
        Event:
            disabled_actions: ['edit', 'new']
            class: App\Entity\Event
            list:
                fields: ['name','owner', 'dateStart', 'dateFinish', 'address', 'reports']
            show:
                fields: ['name','owner', 'dateStart', 'dateFinish', 'address', 'description', 'commentaries', 'reports']
        Association:
            disabled_actions: ['edit', 'new']
            class: App\Entity\Association
            list:
                fields: ['name','owner', 'address', 'pendding', 'reports']
            show:
                fields: ['name','owner', 'address', 'description', 'pendding', 'commentaries', 'reports']
                actions:
                    - { name: 'accept_Admin', type: 'route', css_class: 'btn btn-primary', template: 'admin/admin_accept_action.html.twig'}
        Commentary:
            disabled_actions: ['edit', 'new']
            class: App\Entity\Commentary
            list:
                fields: ['owner','createdAt', 'reports']
            show:
                fields: ['owner', 'createdAt', 'updatedAt', 'commentary', 'party', 'event', 'association', 'reports']
        OpenReport:
            disabled_actions: ['edit', 'new']
            class: App\Entity\Report
            list:
                fields: ['owner', 'date']
                dql_filter: 'entity.solved = false'
            show:
                fields: ['owner','date', 'reason', 'solved', 'commentary', 'association', 'event', 'party', 'user']
                actions:
                    - { name: 'closed_Admin', type: 'route', icon: 'plus-square', css_class: 'btn btn-primary'}
        ClosedReport:
            disabled_actions: ['edit', 'new']
            class: App\Entity\Report
            list:
                fields: ['owner', 'date']
                dql_filter: 'entity.solved = true'
            show:
                fields: ['owner','date', 'reason', 'solved', 'commentary', 'association', 'event', 'party', 'user']
