easy_admin:
    disabled_actions: ['new']
    entities:
#        # List the entity class name you want to manage
        # - App\Entity\User
        # - App\Entity\Game
        # - App\Entity\Party
        # - App\Entity\Event
        # - App\Entity\Association
        # - App\Entity\Commentary

        Game:
            class: App\Entity\Game
            actions: ['new']
    user:
        display_avatar: false
        name_property_path: 'pseudonym'
