twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        discord_link: '%env(DISCORD_LINK)%'
        atjdr_mail: '%env(ATJDR_MAIL)%'
        facebook_link: '%env(FACEBOOK_LINK)%'
        twitter_link: '%env(TWITTER_LINK)%'